<?php
/**
 * Copyright 2008-2015 OPPO Mobile Comm Corp., Ltd, All rights reserved.
 *
 * FileName: AsyncSqlWorker.php
 * Author: liupeng
 * Date: 10/29/15
 */

namespace yii\liuxy\gearman;

/**
 * 异步执行sql
 * Class AsyncSqlWorker
 * @package yii\liuxy\gearman
 */
abstract class AsyncSqlWorker extends Worker {
    /**
     * 多少条执行一次
     * @var int
     */
    protected $step = 1;
    /**
     * 待执行的SQL语句
     * @var array
     */
    protected $sqlArray = [];
    /**
     * 访问的数据库连接
     * @var null
     */
    protected $db = null;

    protected function release() {
        if (count($this->sqlArray) > 0) {
            $this->executeSql();
        }
        parent::release(); // TODO: Change the autogenerated stub
    }


    public function daemonExecute($job) {
        $workload = $job->workload();
        $workload_size = $job->workloadSize();

        if (strlen($workload) != $workload_size)
            return false;
        if ($this->db == null) {
            return false;
        }
        $this->sqlArray[] = $workload;
        if (count($this->sqlArray) >= $this->step) {
            $this->executeSql();
        }
    }

    private function executeSql() {
        $db = $this->db;
        /**
         * @var $dbObject \yii\db\Connection
         */
        $dbObject = \Yii::$app->$db;
        if (!$dbObject->getIsActive()) {
            $dbObject->open();
        }
        foreach($this->sqlArray as $sql) {
            $dbObject->createCommand($sql)->execute();
            \Yii::info($sql, __METHOD__);
        }
        unset($this->sqlArray);
    }

    protected function cleanUp() {
        if ($this->db == null) {
            return false;
        }
        $db = $this->db;
        /**
         * @var $dbObject \yii\db\Connection
         */
        $dbObject = \Yii::$app->$db;
        if ($dbObject == null) {
            return false;
        }
        if ($dbObject->getIsActive()) {
            $dbObject->close();
        }
        return true;
    }
}